name: Build APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        cache: true

    - name: Cache Flutter dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Get Flutter dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Decode Firebase config
      env:
        FIREBASE_CONFIG_BASE64: ${{ secrets.FIREBASE_CONFIG_BASE64 }}
        GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE64 }}
      run: |
        if [ ! -z "$FIREBASE_CONFIG_BASE64" ]; then
          echo $FIREBASE_CONFIG_BASE64 | base64 -d > android/app/google-services.json
        fi

    - name: Build APK (Debug)
      run: flutter build apk --debug

    - name: Build APK (Release)
      run: flutter build apk --release

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: seedfy-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: seedfy-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0-${{ steps.date.outputs.date }}-${{ github.run_number }}
        name: Release v1.0.0-${{ steps.date.outputs.date }}-${{ github.run_number }}
        body: |
          🚀 **Seedfy App Release**
          
          **Changes:**
          - Built from commit: ${{ github.sha }}
          - Build date: ${{ steps.date.outputs.date }}
          
          **Downloads:**
          - Debug APK: For testing and development
          - Release APK: For production use
        files: |
          build/app/outputs/flutter-apk/app-debug.apk
          build/app/outputs/flutter-apk/app-release.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
